name: CI
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12

    - name: Checkout code
      uses: actions/checkout@v1
    
    - name: Verify formatting
      run: |
        UNFMT_FILES=$(gofmt -l .)
        test -z $UNFMT_FILES

    - name: Build
      run: go build
      
    - name: Test
      run: go test ./...
